server:
  port: 8080

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    encryptKey: k1m743hyun

management:
  endpoints:
    web:
      exposure:
        exclude:
          include: '*'
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    com.k1m743hyun.orderservice: DEBUG

spring:
  application:
    name: "order"
  datasource:
    url: ENC(PqBmfh0el1tFGHRhbR/4SQX7QcwBQMMD0DI6n7nNbCcaxqsooIa5ql/dDcQzG23X8w7021xcNCv+vIym+ycN1w==)
    username: ENC(pzqMcuLassmcpZDDr2F8GE9H+EM/cX9O)
    password: ENC(pzqMcuLassmcpZDDr2F8GE9H+EM/cX9O)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    openfeign:
      client:
        config:
          stock:
            url: "stock:8080"
            logger-level: FULL